name: Lint

on: [push, pull_request]

jobs:
    syntax-error-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.11'

            - name: Install Dependencies
              run: |
                  pip install pyflakes nbqa

            - name: Run Pyflakes on Python Files and Notebooks
              run: |
                  pyflakes .
                  nbqa pyflakes .
